### ISSUE TITLE
[TSK-282] Ensure unique file naming scheme

### ISSUE THREAD

**Issue by maany** [dream-aim-deliver/mpi-sda-satellite#8]
We want to make sure that the satellite images scraped for a given job_id and tracer_id are always saved with unique names.
Files which logically contain the same data(same band, geographical location and timestamp), for a given job_id and tracer_id should have the same name.

**Comment by maany** [comment]
The PR will come from Rahul

**Comment by ghost** [comment]
Please provide the status of this activity

**Comment by Rahul-7131** [comment]
Added hash values for images ensuring that images with same content have the same hash value thereby having same names. Completed all the changes, the overall scraper works as intended. Issue is closed from my end, let me know if any changes are needed.

**Comment by ghost** [comment]
@alebg , could you review this ?

**Comment by ghost** [comment]
@alebg , could you review it?

**Comment by ydamit** [comment]
@Deeptikandhol10 , I'm taking over review here!
